// ---------------------------------------------------------------------------
// levels.js — Counterweight levels. Every level is verified solvable by
// tools/solve.js, which also computes `par` and the optimal `solution`.
//
//   par and solution are GENERATED by tools/solve.js — do not hand-edit.
//   #  wall   .  floor   _  gap (a hole through the plate)
//   S  golem   b  stone (weight 3)   g  gem (weight 1)   x  socket
// ---------------------------------------------------------------------------
'use strict';

const LEVELS_CW = [
  {
    name: 'The Pour',
    par: 7,
    solution: 'ULLLURR',
    hint: 'The plate balances on one point. Make a side heavy, and everything loose pours that way.',
    map: [
      '#########',
      '#...b...#',
      '##g....x#',
      '#.....S.#',
      '#########',
    ],
  },
  {
    name: 'The Catch',
    par: 5,
    solution: 'LDRRR',
    hint: 'Your granite feet grip the plate. Stand downhill, and be the wall.',
    map: [
      '###########',
      '#....b....#',
      '#.g......x#',
      '#....S....#',
      '#....b....#',
      '###########',
    ],
  },
  {
    name: 'Counterpoise',
    par: 17,
    solution: 'DRRRULLLLLLLUURRR',
    hint: 'You have weight too. Where you stand is part of the sum.',
    map: [
      '###########',
      '#.b.......#',
      '#.g.....x.#',
      '#....S....#',
      '#.......b.#',
      '###########',
    ],
  },
  {
    name: 'Deadweight',
    par: 20,
    solution: 'LDRULLUULDLDRRRDRUDR',
    hint: 'A stone dropped through a gap is off the scales forever — and the hole it fills becomes floor.',
    map: [
      '###########',
      '#....b....#',
      '#.g._..x..#',
      '#....S....#',
      '#....b....#',
      '###########',
    ],
  },
  {
    name: 'The Ford',
    par: 8,
    solution: 'RRUURDDR',
    hint: 'Sacrifice a stone to the void, and walk across its grave.',
    map: [
      '###########',
      '#.......b.#',
      '#..g.b_..x#',
      '#....S....#',
      '#.b.......#',
      '###########',
    ],
  },
  {
    name: 'Avalanche',
    par: 5,
    solution: 'RRUDD',
    hint: 'One push, many consequences. Read the whole cascade before you lean.',
    map: [
      '###########',
      '#b...x...b#',
      '#....g...._',
      '#..S......#',
      '#....g...._',
      '#b...x...b#',
      '###########',
    ],
  },
  {
    name: 'Twin Pans',
    par: 19,
    solution: 'ULLDLUDDLRRRRRRURRU',
    hint: 'Two gems, two sockets, one balance. Order is everything.',
    map: [
      '###########',
      '#x.......x#',
      '#..g...g..#',
      '#....S....#',
      '#....b....#',
      '###########',
    ],
  },
  {
    name: 'The Last Grain',
    par: 21,
    solution: 'LLLLDDRUURRRRRRRUULDD',
    hint: 'Everything at once: pour, catch, plug, and balance.',
    map: [
      '###########',
      '#..b...b..#',
      '#.x._...g.#',
      '#....S....#',
      '#.g..._.x.#',
      '#..b...b..#',
      '###########',
    ],
  },
];

if (typeof module !== 'undefined' && module.exports) module.exports = LEVELS_CW;
